spring.application.name=messaging_back
spring.datasource.url=jdbc:postgresql://localhost:5432/messaging_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update